from tkinter import *
def func1():
    x=e1.get()
    y=e2.get()
    l3.configure(text=x+" "+y)
root=Tk()
l1=Label(root, text="First Name")
l2=Label(root, text="Last Name")
e1=Entry(root)
e2=Entry(root)
l3=Label(root)
b1=Button(root, text="Show", command=func1)
b2=Button(root, text="Exit", command=sys.exit)
l1.grid(row=0,column=0)
e1.grid(row=0,column=1)
l2.grid(row=1,column=0)
e2.grid(row=1,column=1)
l3.grid(row=2)
b1.grid(row=3,column=0)
b2.grid(row=3,column=1)
root.mainloop()