from tkinter import *
def func1():
    x=s1.get()
    y=s2.get()
    z=x+" "+y
    e3.insert(0,z)
root=Tk()
s1=StringVar()
s2=StringVar()
l1=Label(root, text="First Name")
l2=Label(root, text="Last Name")
e1=Entry(root, textvariable=s1)
e2=Entry(root, textvariable=s2)
l3=Label(root, text="You Typed")
e3=Entry(root)
b1=Button(root, text="Show", command=func1)
b2=Button(root, text="Exit", command=sys.exit)
l1.grid(row=0,column=0)
e1.grid(row=0,column=1)
l2.grid(row=1,column=0)
e2.grid(row=1,column=1)
l3.grid(row=2, column=0, sticky=W)
e3.grid(row=2,column=1)
b1.grid(row=3,column=0)
b2.grid(row=3,column=1)
root.mainloop()